### ISSUE TITLE
Updates over issue

### ISSUE THREAD

**Issue by miguelfs** [bclymer/ios-preferredinput-crash#1]
Hi, @bclymer. Thanks for documenting this bug and writing this sample application :)

I'm also struggling with the .setPreferredInput(...) OS mismanagement when disconnecting a wired EarPods microphone. I was also developing another [sample application ](https://github.com/miguelfs/audioroute_poc)when I discovered your Stack Overflow question, which I put a [bounty](https://stackoverflow.com/questions/65045877/avaudiosession-services-reset-when-capturing-input-from-bluetooth-device-that-di?noredirect=1&lq=1) in the hope of more clarification.

Have you had any updates over it?

Best regards!

**Comment by bclymer** [comment]
Unfortunately I never found a workaround. Eventually I had to move on from this issue to continue development, and documented the behavior. 

I do prevent the services crash I do rely on Apple's documented behavior that `AVAudioSession` will select the last attached device as the route when the preferred input is `nil`. So if a user wants to use a bluetooth mic, I will set the preferred input to `nil`, and if they want to use one of the built-in mics I will set the preferred input to that mic. Since the built-in mics can not suddenly disconnect it's not an issue.

It's not great though, because if there are 2 bluetooth devices, or a bluetooth device and a wired headset, I can let choose between the 2 and must select only the most recently connected device.
